# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol-adapter-common-v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n protocol-adapter-common-v1.proto\x12\x18\x63\x63\x61i.vsg.recogntition.v1\"&\n\x05\x42oost\x12\x10\n\x08keywords\x18\x01 \x03(\t\x12\x0b\n\x03ids\x18\x02 \x03(\t\"*\n\tForbidden\x12\x10\n\x08keywords\x18\x01 \x03(\t\x12\x0b\n\x03ids\x18\x02 \x03(\t\"\xa4\x01\n\x07Segment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12$\n\x1cstart_offset_in_milliseconds\x18\x02 \x01(\r\x12\"\n\x1a\x65nd_offset_in_milliseconds\x18\x03 \x01(\r\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12-\n\x05words\x18\x05 \x03(\x0b\x32\x1e.ccai.vsg.recogntition.v1.Word\"^\n\x04Word\x12\x0c\n\x04text\x18\x01 \x01(\t\x12$\n\x1cstart_offset_in_milliseconds\x18\x02 \x01(\r\x12\"\n\x1a\x65nd_offset_in_milliseconds\x18\x03 \x01(\r*g\n\x0b\x41udioFormat\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\"\n\x1e\x41UDIO_L16_RATE_8000_CHANNELS_1\x10\x01\x12#\n\x1f\x41UDIO_L16_RATE_16000_CHANNELS_1\x10\x02*x\n\x08Language\x12\x06\n\x02KO\x10\x00\x12\x06\n\x02JA\x10\x01\x12\x06\n\x02\x45N\x10\x02\x12\t\n\x05ZH_CN\x10\x03\x12\t\n\x05ZH_TW\x10\x04\x12\x06\n\x02\x45S\x10\x05\x12\x06\n\x02\x46R\x10\x06\x12\x06\n\x02RU\x10\x07\x12\x06\n\x02VI\x10\x08\x12\x06\n\x02TH\x10\t\x12\x06\n\x02ID\x10\n\x12\x06\n\x02\x44\x45\x10\x0b\x12\x06\n\x02IT\x10\x0c\x62\x06proto3')

_AUDIOFORMAT = DESCRIPTOR.enum_types_by_name['AudioFormat']
AudioFormat = enum_type_wrapper.EnumTypeWrapper(_AUDIOFORMAT)
_LANGUAGE = DESCRIPTOR.enum_types_by_name['Language']
Language = enum_type_wrapper.EnumTypeWrapper(_LANGUAGE)
UNSPECIFIED = 0
AUDIO_L16_RATE_8000_CHANNELS_1 = 1
AUDIO_L16_RATE_16000_CHANNELS_1 = 2
KO = 0
JA = 1
EN = 2
ZH_CN = 3
ZH_TW = 4
ES = 5
FR = 6
RU = 7
VI = 8
TH = 9
ID = 10
DE = 11
IT = 12


_BOOST = DESCRIPTOR.message_types_by_name['Boost']
_FORBIDDEN = DESCRIPTOR.message_types_by_name['Forbidden']
_SEGMENT = DESCRIPTOR.message_types_by_name['Segment']
_WORD = DESCRIPTOR.message_types_by_name['Word']
Boost = _reflection.GeneratedProtocolMessageType('Boost', (_message.Message,), {
  'DESCRIPTOR' : _BOOST,
  '__module__' : 'protocol_adapter_common_v1_pb2'
  # @@protoc_insertion_point(class_scope:ccai.vsg.recogntition.v1.Boost)
  })
_sym_db.RegisterMessage(Boost)

Forbidden = _reflection.GeneratedProtocolMessageType('Forbidden', (_message.Message,), {
  'DESCRIPTOR' : _FORBIDDEN,
  '__module__' : 'protocol_adapter_common_v1_pb2'
  # @@protoc_insertion_point(class_scope:ccai.vsg.recogntition.v1.Forbidden)
  })
_sym_db.RegisterMessage(Forbidden)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENT,
  '__module__' : 'protocol_adapter_common_v1_pb2'
  # @@protoc_insertion_point(class_scope:ccai.vsg.recogntition.v1.Segment)
  })
_sym_db.RegisterMessage(Segment)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {
  'DESCRIPTOR' : _WORD,
  '__module__' : 'protocol_adapter_common_v1_pb2'
  # @@protoc_insertion_point(class_scope:ccai.vsg.recogntition.v1.Word)
  })
_sym_db.RegisterMessage(Word)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOFORMAT._serialized_start=409
  _AUDIOFORMAT._serialized_end=512
  _LANGUAGE._serialized_start=514
  _LANGUAGE._serialized_end=634
  _BOOST._serialized_start=62
  _BOOST._serialized_end=100
  _FORBIDDEN._serialized_start=102
  _FORBIDDEN._serialized_end=144
  _SEGMENT._serialized_start=147
  _SEGMENT._serialized_end=311
  _WORD._serialized_start=313
  _WORD._serialized_end=407
# @@protoc_insertion_point(module_scope)
